### PR TITLE
Use Promise api if available for simple getValue calls like isEnabled()

### PR DESCRIPTION
**Pull request by kellycampbell**
If Promises are available and the caller doesn't pass any callbacks, this will return a Promise for the following functions:

isEnabled
enable
isConnected
disconnect
stopScan
showBluetoothSettings

### CODE REVIEW

**Comment by rrharvey** [comment]
I would suggest having a consistent API with all functions returning promises. It would be confusing to have a mixed bag. 

I've wrapped this plugin for quite a while in this way. I still use a callbacks (a basic event emitter might be nice too) for notifications and peripheral discovery. The scan promise is resolved when the scan completes. The startNotification promise is resolved immediately to indicate that notifications have been turned on. 

The connect call is a little different. Right now I resolve the connect promise when the connection is successful. I return an object that contains a "disconnected" property that is another promise that is resolved if you get disconnected.

**Comment by halindrome** [comment]
I like the disconnected property approach.  Promises make the resulting
code so much cleaner.

On Sat, Dec 5, 2015 at 12:40 PM, Ryan Harvey <notifications@github.com>
wrote:

> I would suggest having a consistent API with all functions returning
> promises. It would be confusing to have a mixed bag.
>
> I've wrapped this plugin for quite a while in this way. I still use a
> callbacks (a basic event emitter might be nice too) for notifications and
> peripheral discovery. The scan promise is resolved when the scan completes.
> The startNotification promise is resolved immediately to indicate that
> notifications have been turned on.
>
> The connect call is a little different. Right now I resolve the connect
> promise when the connection is successful. I return an object that contains
> a "disconnected" property that is another promise that is resolved if you
> get disconnected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/don/cordova-plugin-ble-central/pull/133#issuecomment-162233945>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by don** [comment]
@kellycampbell I'm hoping to get to this after Christmas, sorry about the delay

**Comment by kellycampbell** [comment]
I'm reworking this to be more of a wrapper probably like @rrharvey described. I wanted to get some feedback on the interfaces because many functions are able to callback multiple times and/or call a failure callback after a success callback has been called (e.g. disconnected).

The simplest way would be to just keep those functions using callbacks and not return promises. 

Another possibility is to have the scan functions return something like an observable or even a generator. 

I'm leaning towards the simpler solution since that is how this original patch was setup and hence it's what I'm using in a production app.

Thoughts?

**Comment by don** [comment]
See #247

**Pull request closed without merging**
