### PR TITLE
Patch/cb central manager 2

### PR DESCRIPTION
**Pull request by jospete**
CBCentralManager initialization fix per this comment:
https://github.com/don/cordova-plugin-ble-central/issues/739#issuecomment-619149028

### CODE REVIEW

**Comment by leighwoltman** [comment]
I've tested this change and agree that it does the trick - I was running into the same issue as the author. Thanks for this!

**Comment by QuentinFarizon** [comment]
It doesn't work for me ... What am I missing ? 

I have updated my plugin to the version of this MR, and added to package.json :
```
"cordova-plugin-ble-central":` {
        "IOS_INIT_ON_LOAD": "false"
},
```

**Comment by leighwoltman** [comment]
May need to check that your config.xml includes it, and then check downstream to the output files created by Cordova to see if you've actually picked up this variable.

`<plugin name="cordova-plugin-ble-central" ...>
        <variable name="BLUETOOTH_USAGE_DESCRIPTION" ... />
        <variable name="IOS_INIT_ON_LOAD" value="false" />
    </plugin>`

**Comment by QuentinFarizon** [comment]
Sorry, after cleaning all output first it worked indeed. Thanks =

**Comment by don** [comment]
@jospete this is great solution, so much simpler than what we were trying with #735.

**Pull request merged**
