### PR TITLE
Fix for #473

### PR DESCRIPTION
**Pull request by jedthehumanoid**

### CODE REVIEW

**Comment by don** [comment]
#473

**Comment by QuentinFarizon** [comment]
Would love to see this merged, I'm encountering the issue on a number of client devices (Samsung Galaxy Tab A for example)

What is still needed for a merge ? Additional testing ? Just fixing the conflict ? 

Thanks for your work anyway @jedthehumanoid @don !

**Comment by QuentinFarizon** [comment]
It's conflicting with https://github.com/don/cordova-plugin-ble-central/commit/ee7cb0dbeff237af37faeee97c50bfd2eb430497 but is this still needed now ?

**Comment by peitschie** [comment]
@QuentinFarizon I agree that the linked commit there looks like it should have impacted this issue.
If you are still finding this failure, please feel free to raise a new issue with stack traces and I'll dig into it some more.

**Pull request closed without merging**
