### PR TITLE
Added ability to read RSSI value from an active BLE connection.

### PR DESCRIPTION
**Pull request by chris-armstrong**
Please find attached the code for a new function to read the RSSI value from an active BLE connection.

### CODE REVIEW

**Comment by furnaceX** [comment]
Hi Chris, why do you queue the read rssi command?  Unless I'm not understanding BLE properly, I don't think you need to queue it as it's not actually a call to the remote device.  I've done something similar without queueing, so far just for android.  Is there a reason to queue on iOS?

**Comment by chris-armstrong** [comment]
The queuing behavior is to handle multiple calls to the readRSSI API - the API is asynchronous, so multiple calls need multiple callback handlers to be registered, especially where the client code is arranged in a polling configuration. Client code that depends on it's callback handler being invoked (e.g. when a promise-based wrapper is used with cordova-plugin-ble-central) can be left in a broken state if neither the success or failure handler is invoked.

**Comment by giuseppe27** [comment]
Hi,
I applied your modify to the code. I rebuild the application in node.js but when the APP run take a no-method error:

`TypeError: Object #<Object> has no method 'readRSSI'`

What am I doing wrong?

**Comment by chris-armstrong** [comment]
TBH, not sure, you may need to perform
cordova platform ios remove
cordova platform ios add

for it to update the JS www/ file.

**Comment by giuseppe27** [comment]
I use Android. Yes deleting android folder and rebuild app it works. But with phonegap developer app.

**Comment by don** [comment]
@chris-armstrong Thanks for the pull request. Sorry it took so long to merge

**Comment by don** [comment]
@giuseppe27 This won't work with the [PhoneGap Developer App](http://app.phonegap.com) for a while. I just merged the changes into master today. Soon, I'll push a plugin release to NPM. At some point in the future Adobe will do a new build of PhoneGap Developer App that includes the updated version of the plugin. Once that new version is released, readRSSI will work. 

If you need readRSSI now, you'll need to install the plugin from github and build locally.

     phonegap add plugin https://github.com/don/cordova-plugin-ble-central.git

If you're using PhoneGap Developer app for fast build/deployment, you can build a new version of that app from [source](https://github.com/phonegap/phonegap-app-developer) with an updated version of this plugin.

**Pull request merged**
