### PR TITLE
﻿Add new bluetooth permissions on plugin.xml (BLUETOOTH_SCAN, BLUETOOTH_CONNECT)

### PR DESCRIPTION
**Pull request by LDLCLid3**
Add Permissions requests on Scan, connect and autoconnect method.

### CODE REVIEW

**Comment by peitschie** [comment]
This looks great @LDLCLid3 

I'll hopefully get a chance to look at this in the next week or so... but so far, no immediate points of concern with what you've done here 😺

**Comment by peitschie** [comment]
Just noting this is related to #875

**Comment by pelkamarcin** [comment]
Hi, @peitschie You think this could be merged soon?

**Comment by peitschie** [comment]
It's definitely on my todo list @pelkamarcin ... unfortunately, the approach here actually breaks forward compatibility if an application is build with a targetSDK of 30, and is then deployed on Android 12.

I haven't yet figured out a clean solution to cope with this case.

**Pull request closed without merging**
