### PR TITLE
Correctly disconnect any started peripherals on Cordova destroy or reset

### PR DESCRIPTION
**Pull request by peitschie**

### CODE REVIEW

**Comment by peitschie** [comment]
Without this, Android may leave the BLE connection open so scanning no longer shows the device.

**Comment by tigohenryschultz** [comment]
Can this get merged?

**Comment by peitschie** [comment]
Hi @tigohenryschultz 

Which issue are you hitting that this might help with?

**Comment by peitschie** [comment]
Ah. That issue I've attempted to rectify in https://github.com/don/cordova-plugin-ble-central/pull/892

See https://github.com/don/cordova-plugin-ble-central/pull/892/commits/3119d1f0f0f2ea018f1a838840957577ef4e4f58

It's worth noting that several Android phones actually won't drop the BLE connection when Bluetooth is turned off on the phone. I've verified that the peripheral can sometimes remain connected even though Android is claiming Bluetooth is off. This could be what you're seeing here too.

**Comment by peitschie** [comment]
This may address part of the issue raised in #464

**Pull request merged**
