### PR TITLE
register for callbacks on Bluetooth state change

### PR DESCRIPTION
**Pull request by rrharvey**
Adds support for getting notified of changes to Bluetooth state on the device.

### CODE REVIEW

**Comment by rrharvey** [comment]
Found some bugs. I might submit a new one later.

**Comment by don** [comment]
@rrharvey thanks for this pull request, hopefully I'll get this merged in soon, but I probably won't have time until after Christmas

**Comment by zabojad** [comment]
Hi there !
@don do you think you could merge it soon ?
I need this feature on a current project...
Best,
Tom

**Comment by don** [comment]
Hopefully soon. I need to get time to test it. Until then run off @rrharveys' branch.

**Comment by don** [comment]
@rrharvey Thanks for this pull request! Sorry it took so long to merge.

**Pull request merged**
