### PR TITLE
Patch/ios cb manager

### PR DESCRIPTION
**Pull request by jospete**
Fixes issue on iOS where authorization request was happening on app load, due to initializing the CBCentralManager in the plugin initialize method.

This workaround wraps the manager reference as a getter/setter, which is not initialized until the first time the plugin requests it.

### CODE REVIEW

**Comment by don** [comment]
I like this idea, but it's causing an error when scan initializes CBCentralManager. I think it's a timing issue because the manager returned to scan is in an unknown state.

You can duplicate it using this project
https://github.com/don/ITP-BluetoothLE/tree/master/phonegap/connect

```
2020-04-19 13:38:40.647300-0400 Connect[400:13844] Finished load of: file:///private/var/containers/Bundle/Application/29A1A35E-A69C-4911-A508-105F79216098/Connect.app/www/index.html
2020-04-19 13:38:40.662814-0400 Connect[400:13844] scan
2020-04-19 13:38:40.664041-0400 Connect[400:13844] Status of CoreBluetooth central manager changed 0 State unknown (CBCentralManagerStateUnknown)
2020-04-19 13:38:40.664118-0400 Connect[400:13844] [CoreBluetooth] API MISUSE: <CBCentralManager: 0x282435030> can only accept this command while in the powered on state
2020-04-19 13:38:40.675032-0400 Connect[400:13844] Status of CoreBluetooth central manager changed 5 State powered up and ready (CBCentralManagerStatePoweredOn)
2020-04-19 13:38:45.665070-0400 Connect[400:13844] stopScanTimer
```

iPhone 7
iOS 13.4.1
macOS 10.15.4 (19E287) with Xcode 11.4.1 (11E503a)
Cordova 9.0.0 (cordova-lib@9.0.1)
cordova-plugin-ble-central  https://github.com/jospete/cordova-plugin-ble-central/tree/05ab7913385ff131f10e3fea9efc3d348ac89b0e

**Comment by jospete** [comment]
@don  would you mind testing again with the updated branch? I don't have access to an iOS device for testing at the moment.

The update should halt any manager reference requests until the manager's state becomes known

**Comment by don** [comment]
@jospete that didn't work reliably. If I added some log statements and increased the timeout it usually worked. 

I think the proper way to do this is to wait for `centralManagerDidUpdateState:central` to be called. I don't know how to delay `[self manager]` until the callback is called. Any ideas?

**Comment by jospete** [comment]
@don you could add an internal blocking boolean flag, and set it to true once `centralManagerDidUpdateState:central` gets called.

Then you can change the internal `managerHasValidState` method to just return the state of the flag, and the blocking loop should happen automatically when `[self manager]` gets called.

You will probably need to increase the max tries to something like 50 in the loop here -> https://github.com/jospete/cordova-plugin-ble-central/blob/patch/ios-cb-manager/src/ios/BLECentralPlugin.m#L69

**Comment by jospete** [comment]
@don I updated the PR with the suggestions in my previous comment - let me know if that code works any better

**Comment by don** [comment]
@jospete unfortunately that didn't work either. 

While waiting for the `_manager` to initialize, we need to block here
https://github.com/jospete/cordova-plugin-ble-central/blob/eb8b8f98a6a6cf7e205dd9bacf3a786720eb5c38/src/ios/BLECentralPlugin.m#L91

[waitForValidManagerState](https://github.com/jospete/cordova-plugin-ble-central/blob/eb8b8f98a6a6cf7e205dd9bacf3a786720eb5c38/src/ios/BLECentralPlugin.m#L64-L79) *should* be doing that, but it doesn't work. The code always hits `maxBlockingCycles` because [centralManagerDidUpdateState:central](https://github.com/jospete/cordova-plugin-ble-central/blob/eb8b8f98a6a6cf7e205dd9bacf3a786720eb5c38/src/ios/BLECentralPlugin.m#L64-L79) in the delegate is never called when we're in that loop. I think this is because everything is happening on the main thread.

**Comment by jospete** [comment]
I think someone has proposed a much simpler solution regarding how the plugin is loaded. Not sure if that will fix the instantiation problem, but if so it would be much less harsh of a change than mine :)

https://github.com/don/cordova-plugin-ble-central/issues/739#issuecomment-619149028

**Comment by jospete** [comment]
@don I've opened a new PR for this with much lower-impact changes:
https://github.com/don/cordova-plugin-ble-central/pull/769

Can you please verify that installing the plugin with IOS_INIT_ON_LOAD = false delays the dialog?
(Also, is that a good plugin variable name or should it be something else?)

**Pull request closed without merging**
