### PR TITLE
change errorType in ios 'didWriteValueForCharacteristic:error:'

### PR DESCRIPTION
**Pull request by daskonsti**
In the android part, the "write" call returns "status" as int, if an error occurs. In iOS, there is a "localizedDescription" and so on js layer it's not possible to catch an equal code. So in the first step it would be logical, to send from both platforms the code, so the custom JS can handle the error in it's favour. In the second step, it could be better to return a JSON object with a structure like 
error:
{
    code: int,
    localizedDescription: string
    [...]
}

### CODE REVIEW

**Comment by don** [comment]
This is a good idea, but it'll need to be implemented on iOS and Android before I merge.

**Comment by deepak90mu** [comment]
Hi,

From the hardware they are trying to send 800KB wav data to mobile.
Is it possible to get the whole data using ble.startnotification method??
Because when i tried am getting only 10 kb data.

Thanks in advance.

**Comment by don** [comment]
@deepak90mu please create a new issue with your question

**Comment by peitschie** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
