### PR TITLE
scan fix for android 10 and above REQUEST_ACCESS_FINE_LOCATION

### PR DESCRIPTION
**Pull request by subratpalhar92**
scan fix for android 10 and above REQUEST_ACCESS_FINE_LOCATION

### CODE REVIEW

**Comment by subratpalhar92** [comment]
Android 10 & above have scan issue if fine location is not enabled

https://developer.android.com/guide/topics/connectivity/bluetooth-le

**Comment by tompap** [comment]
+1 to integrate this !

**Comment by CodeTroopers** [comment]
@don Could you merge this fix, please?

**Comment by markamccorkle** [comment]
> @don Could you merge this fix, please?

You can use my fork if you'd like. I have no idea why this hasn't been merged. I checked it months ago and it works fine for me on all devices, OS versions, etc. 
`    "cordova-plugin-ble-central": "github:EdibuLLC/cordova-plugin-ble-central",`

**Comment by hschultz1960** [comment]
How does one go about specifying your fork in the `config.xml` file? 
It seems that the cordova CLI itself supports GitHub URL's, but is that supported inside the XML also?

**Comment by favnec5** [comment]
@markamccorkle 
thanks a lot, Good job, it work.

**Comment by angel-garcia-lopez** [comment]
This needs to be merged now. This fixes the scan problem in Android 10. I did the same changes myself locally and got it working.

**Comment by MikeMather** [comment]
Any news on this? This is causing a lot of issues for us so if there's anyone that can merge this soon it'd be greatly appreciated.

**Comment by niclaforge** [comment]
Following up on this? PR seems to have no tracking motion for months and deadline from Android is at the door. @don anyway you can merge it or have someone on the project to have a look? Appreciate it.

**Comment by don** [comment]
This is similar to #771

**Comment by don** [comment]
@subratpalhar92 thanks for this PR, sorry it took so long to get to it. I'm closing because these changes were handled in #771. I'm using that version because it also allows the user to choose the background permission. The new code is published to npm as v1.3.0. 

ble-central-location-Q

**Comment by giowild** [comment]
Hi all, since you are experts about BLE, ionic and Background, I have the following issue:

https://github.com/don/cordova-plugin-ble-central/issues/850

Any advise or pointer would be greatly appreciated, thanks a lot!

**Pull request closed without merging**
