### PR TITLE
Add duration flag (in seconds) to scan with options

### PR DESCRIPTION
**Pull request by peitschie**
This allows different scan modes to be easily selected while still allowing the scan to be time-limited

### CODE REVIEW

**Comment by mikerusso-tsi** [comment]
Looks like you're cut off the 'scan' function, which will force all consumers of that to switch.  Do you normally want a deprecation period to ease people over?  I.e., change 'scan' to internally call 'startScanWithOptions'.

**Comment by peitschie** [comment]
Both`scan` and `startScan` remain fully supported. If you pay close attention to ble.js, you'll see that I've routed these to the equivalent `scanWithOptions` call instead, as all the native paths trace through the same code.

**Comment by mikerusso-tsi** [comment]
> Both`scan` and `startScan` remain fully supported. If you pay close attention to ble.js, you'll see that I've routed these to the equivalent `scanWithOptions` call instead, as all the native paths trace through the same code.

Ah, that's what I was expecting!  Sorry.
But is the @slim variant included in this PR?  I'm hoping so!

**Comment by peitschie** [comment]
Slim runs on a different branch. I'll publish both at the same time once I merge this 🙂

**Pull request merged**
